version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start # Or replace with npm run start if required
